### PR TITLE
wip: build rust project & travis CI setup

### LINKED ISSUE #4: Make project on Windows
Makefile support on Windows is lacking, so in order to build on Windows another workflow is needed.

See https://github.com/pornel/dssim/issues/26

### PR DESCRIPTION
**Pull request by awerlang**
This is a work in progress. This needs some help to get it done.

- output is inside `vendor/release/build`: the gotcha is the filename isn't deterministic, something random is appended to it
- Travis CI doesn't supports Windows builds
- AppVeyor does, but doesn't support Rust
- No NPM publishing yet but it should be part of it I guess
- At least it should now be possible to build on Windows locally, given Rust & dependencies are installed

Closes #4

### CODE REVIEW

**Comment by fhemberger** [comment]
Wow, thanks! This looks great already.

So I think the only thing I need to add is:
- instead of ` ls vendor/release/build`,
  ```
  mv  vendor/release/build/dssim-* vendor/dssim-`uname | tr '[:upper:]' '[:lower:]'`
  ```

  adds `darwin` or `linux` (can't use TRAVIS_OS_NAME in this case) – precompiled binaries should be included in the release
- In `lib/install.js`, check if there's already a file `dssim-${process.platform}` and skip compilation
- Get the binaries into the npm release (without `vendor/release/*`), https://docs.travis-ci.com/user/deployment/npm/

Right?

**Comment by awerlang** [comment]
The current issue is identifying the correct output

- cargo build --release
  - produces dssim-abfa771b3e367bdd	_and_ dssim-b570b544a7581cc3
- cargo build --release --bin dssim
  - error: no bin target named `dssim`
- cargo build --release --bin main
  - error: no bin target named `main`
- cargo build --release --bins
  - no output

It may be related to a convention where programs should be placed inside `src/bin` but in the archive both `main.rs` and `lib.rs` are in the same directory.

After this, is it possible to deploy to npm binaries produced in separate jobs (linux & os x) straight from travis?

**Comment by fhemberger** [comment]
Ok, found one source of the problem. You were still [pulling v1.3.3 of dssim](https://github.com/awerlang/dssim-bin/blob/47716984dd3f814b6a25104074f50501c6cc5732/package.json#L3), not the 2.x release. I map the dssim version number to the version of this package.

Updating to the current 2.9.4 release gives me a proper binary: `vendor/release/dssim`.
See https://github.com/fhemberger/dssim-bin/pull/6 for my test PR.

**Comment by awerlang** [comment]
You're right! But still this is the output in travis:

```
$ ls vendor/release/build
rayon-core-29a42b65b777dc05  rayon-core-af02fc9cf039ecce
```

**Comment by awerlang** [comment]
Another option, as suggested to me on S.O., is to use the `cargo install` command directly.

`cargo install dssim --version ${version}`

Only I don't know how we could pass the version to travis.

**Comment by fhemberger** [comment]
Binary is in `vendor/release`, not `vendor/release/build`.

**Comment by awerlang** [comment]
Great

**Comment by fhemberger** [comment]
@awerlang Sorry it took so long, merged your PR. Thanks!
I'm not sure yet how to proceed with the Rust build.

**Pull request merged**
